// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillSwap.Data;

#nullable disable

namespace SkillSwap.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260319054346_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SkillSwap.Data.Entities.StudentEntity", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SkillSwap.Data.Entities.TalentEntity", b =>
                {
                    b.Property<Guid>("TalentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProficiencyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TalentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TalentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Talents");
                });

            modelBuilder.Entity("SkillSwap.Data.Entities.TradeRequestEntity", b =>
                {
                    b.Property<Guid>("TradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OfferedTalentId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestedTalentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TalentEntityTalentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetStudentId")
                        .HasColumnType("TEXT");

                    b.HasKey("TradeId");

                    b.HasIndex("OfferedTalentId");

                    b.HasIndex("RequestedTalentId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("TalentEntityTalentId");

                    b.HasIndex("TargetStudentId");

                    b.ToTable("TradeRequests");
                });

            modelBuilder.Entity("SkillSwap.Data.Entities.TalentEntity", b =>
                {
                    b.HasOne("SkillSwap.Data.Entities.StudentEntity", "Owner")
                        .WithMany("Talents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SkillSwap.Data.Entities.TradeRequestEntity", b =>
                {
                    b.HasOne("SkillSwap.Data.Entities.TalentEntity", "OfferedTalent")
                        .WithMany()
                        .HasForeignKey("OfferedTalentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSwap.Data.Entities.TalentEntity", "RequestedTalent")
                        .WithMany()
                        .HasForeignKey("RequestedTalentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSwap.Data.Entities.StudentEntity", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSwap.Data.Entities.TalentEntity", null)
                        .WithMany("TradeRequests")
                        .HasForeignKey("TalentEntityTalentId");

                    b.HasOne("SkillSwap.Data.Entities.StudentEntity", "TargetStudent")
                        .WithMany()
                        .HasForeignKey("TargetStudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OfferedTalent");

                    b.Navigation("RequestedTalent");

                    b.Navigation("Requester");

                    b.Navigation("TargetStudent");
                });

            modelBuilder.Entity("SkillSwap.Data.Entities.StudentEntity", b =>
                {
                    b.Navigation("Talents");
                });

            modelBuilder.Entity("SkillSwap.Data.Entities.TalentEntity", b =>
                {
                    b.Navigation("TradeRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
